// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJECT.Data;

#nullable disable

namespace PROJECT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROJECT.Data.Alert", b =>
                {
                    b.Property<int>("alert_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("alert_id"));

                    b.Property<string>("alert_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("appliance_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_resolved")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("severity")
                        .HasColumnType("float");

                    b.HasKey("alert_id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("PROJECT.Data.Appliance", b =>
                {
                    b.Property<int>("appliance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appliance_id"));

                    b.Property<string>("device_identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("home_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("installed_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type_id")
                        .HasColumnType("int");

                    b.HasKey("appliance_id");

                    b.HasIndex("home_id");

                    b.HasIndex("type_id");

                    b.ToTable("Appliances");
                });

            modelBuilder.Entity("PROJECT.Data.ApplianceType", b =>
                {
                    b.Property<int>("type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("type_id"));

                    b.Property<double>("avg_energy_rating")
                        .HasColumnType("float");

                    b.Property<double>("avg_water_rating")
                        .HasColumnType("float");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("type_id");

                    b.ToTable("ApplianceTypes");
                });

            modelBuilder.Entity("PROJECT.Data.EnergyUsage", b =>
                {
                    b.Property<int>("energy_usage_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("energy_usage_id"));

                    b.Property<int>("appliance_id")
                        .HasColumnType("int");

                    b.Property<double>("cost_estimated")
                        .HasColumnType("float");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<double>("kwh_consumed")
                        .HasColumnType("float");

                    b.Property<double>("peak_usage")
                        .HasColumnType("float");

                    b.HasKey("energy_usage_id");

                    b.ToTable("EnergyUsages");
                });

            modelBuilder.Entity("PROJECT.Data.Home", b =>
                {
                    b.Property<int>("home_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("home_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("home_id");

                    b.HasIndex("user_id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("PROJECT.Data.Notification", b =>
                {
                    b.Property<int>("notification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notification_id"));

                    b.Property<int>("alert_id")
                        .HasColumnType("int");

                    b.Property<int>("channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("read_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("sent_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("notification_id");

                    b.HasIndex("alert_id");

                    b.HasIndex("user_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PROJECT.Data.SensorData", b =>
                {
                    b.Property<int>("Sensor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sensor_id"));

                    b.Property<int>("appliance_id")
                        .HasColumnType("int");

                    b.Property<string>("reading_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timestramp")
                        .HasColumnType("datetime2");

                    b.Property<int>("unit")
                        .HasColumnType("int");

                    b.Property<double>("value")
                        .HasColumnType("float");

                    b.HasKey("Sensor_id");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("PROJECT.Data.SustainabilityScore", b =>
                {
                    b.Property<int>("sustainablity_score_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sustainablity_score_id"));

                    b.Property<double>("energy_score")
                        .HasColumnType("float");

                    b.Property<int>("home_id")
                        .HasColumnType("int");

                    b.Property<double>("overall_score")
                        .HasColumnType("float");

                    b.Property<DateTime>("period_end")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("period_start")
                        .HasColumnType("datetime2");

                    b.Property<double>("water_score")
                        .HasColumnType("float");

                    b.HasKey("sustainablity_score_id");

                    b.HasIndex("home_id");

                    b.ToTable("SustainabilityScores");
                });

            modelBuilder.Entity("PROJECT.Data.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PROJECT.Data.WaterUsage", b =>
                {
                    b.Property<int>("water_usage_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("water_usage_id"));

                    b.Property<int>("appliance_id")
                        .HasColumnType("int");

                    b.Property<double>("cost_estimated")
                        .HasColumnType("float");

                    b.Property<int>("cycle_count")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<double>("liters_consumed")
                        .HasColumnType("float");

                    b.HasKey("water_usage_id");

                    b.ToTable("WaterUsages");
                });

            modelBuilder.Entity("PROJECT.Data.Appliance", b =>
                {
                    b.HasOne("PROJECT.Data.Home", "Home")
                        .WithMany()
                        .HasForeignKey("home_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROJECT.Data.ApplianceType", "ApplianceType")
                        .WithMany()
                        .HasForeignKey("type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplianceType");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("PROJECT.Data.Home", b =>
                {
                    b.HasOne("PROJECT.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PROJECT.Data.Notification", b =>
                {
                    b.HasOne("PROJECT.Data.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("alert_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROJECT.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PROJECT.Data.SustainabilityScore", b =>
                {
                    b.HasOne("PROJECT.Data.Home", "Home")
                        .WithMany()
                        .HasForeignKey("home_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");
                });
#pragma warning restore 612, 618
        }
    }
}
